// Code generated by MockGen. DO NOT EDIT.
// Source: port_out.go

// Package testcase_test is a generated GoMock package.
package testcase_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWdGetter is a mock of WdGetter interface.
type MockWdGetter struct {
	ctrl     *gomock.Controller
	recorder *MockWdGetterMockRecorder
}

// MockWdGetterMockRecorder is the mock recorder for MockWdGetter.
type MockWdGetterMockRecorder struct {
	mock *MockWdGetter
}

// NewMockWdGetter creates a new mock instance.
func NewMockWdGetter(ctrl *gomock.Controller) *MockWdGetter {
	mock := &MockWdGetter{ctrl: ctrl}
	mock.recorder = &MockWdGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWdGetter) EXPECT() *MockWdGetterMockRecorder {
	return m.recorder
}

// GetWd mocks base method.
func (m *MockWdGetter) GetWd() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWd")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWd indicates an expected call of GetWd.
func (mr *MockWdGetterMockRecorder) GetWd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWd", reflect.TypeOf((*MockWdGetter)(nil).GetWd))
}

// MockFileExister is a mock of FileExister interface.
type MockFileExister struct {
	ctrl     *gomock.Controller
	recorder *MockFileExisterMockRecorder
}

// MockFileExisterMockRecorder is the mock recorder for MockFileExister.
type MockFileExisterMockRecorder struct {
	mock *MockFileExister
}

// NewMockFileExister creates a new mock instance.
func NewMockFileExister(ctrl *gomock.Controller) *MockFileExister {
	mock := &MockFileExister{ctrl: ctrl}
	mock.recorder = &MockFileExisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileExister) EXPECT() *MockFileExisterMockRecorder {
	return m.recorder
}

// ExistFile mocks base method.
func (m *MockFileExister) ExistFile(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistFile", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistFile indicates an expected call of ExistFile.
func (mr *MockFileExisterMockRecorder) ExistFile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistFile", reflect.TypeOf((*MockFileExister)(nil).ExistFile), path)
}

// MockPublicDirMaker is a mock of PublicDirMaker interface.
type MockPublicDirMaker struct {
	ctrl     *gomock.Controller
	recorder *MockPublicDirMakerMockRecorder
}

// MockPublicDirMakerMockRecorder is the mock recorder for MockPublicDirMaker.
type MockPublicDirMakerMockRecorder struct {
	mock *MockPublicDirMaker
}

// NewMockPublicDirMaker creates a new mock instance.
func NewMockPublicDirMaker(ctrl *gomock.Controller) *MockPublicDirMaker {
	mock := &MockPublicDirMaker{ctrl: ctrl}
	mock.recorder = &MockPublicDirMakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicDirMaker) EXPECT() *MockPublicDirMakerMockRecorder {
	return m.recorder
}

// MakePublicDir mocks base method.
func (m *MockPublicDirMaker) MakePublicDir(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakePublicDir", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakePublicDir indicates an expected call of MakePublicDir.
func (mr *MockPublicDirMakerMockRecorder) MakePublicDir(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakePublicDir", reflect.TypeOf((*MockPublicDirMaker)(nil).MakePublicDir), path)
}

// MockPublicFileWriter is a mock of PublicFileWriter interface.
type MockPublicFileWriter struct {
	ctrl     *gomock.Controller
	recorder *MockPublicFileWriterMockRecorder
}

// MockPublicFileWriterMockRecorder is the mock recorder for MockPublicFileWriter.
type MockPublicFileWriterMockRecorder struct {
	mock *MockPublicFileWriter
}

// NewMockPublicFileWriter creates a new mock instance.
func NewMockPublicFileWriter(ctrl *gomock.Controller) *MockPublicFileWriter {
	mock := &MockPublicFileWriter{ctrl: ctrl}
	mock.recorder = &MockPublicFileWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicFileWriter) EXPECT() *MockPublicFileWriterMockRecorder {
	return m.recorder
}

// WritePublicFile mocks base method.
func (m *MockPublicFileWriter) WritePublicFile(path string, date []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePublicFile", path, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePublicFile indicates an expected call of WritePublicFile.
func (mr *MockPublicFileWriterMockRecorder) WritePublicFile(path, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePublicFile", reflect.TypeOf((*MockPublicFileWriter)(nil).WritePublicFile), path, date)
}
