// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ppdx999/kyopro/internal/cli"
	"github.com/ppdx999/kyopro/internal/infra"
	"github.com/ppdx999/kyopro/internal/service"
	"github.com/ppdx999/kyopro/internal/service/helper"
	"github.com/ppdx999/kyopro/internal/service/helper/port"
)

// Injectors from wire.go:

func InitializeConsole() infra.Console {
	consoleImpl := infra.NewConsoleImpl()
	return consoleImpl
}

func InitializeGetWd() port.GetWd {
	fsImpl := infra.NewFsImple()
	return fsImpl
}

func InitializeMakePublicDir() port.MakePublicDir {
	fsImpl := infra.NewFsImple()
	return fsImpl
}

func InitializeGetWorkspace() helper.GetWorkspace {
	getWd := InitializeGetWd()
	getWorkspaceImpl := helper.NewGetWorkspaceImpl(getWd)
	return getWorkspaceImpl
}

func InitializeMakeProblemDir() helper.MakeProblemDir {
	makePublicDir := InitializeMakePublicDir()
	getWorkspace := InitializeGetWorkspace()
	makeProblemDirImpl := helper.NewMakeProblemDirImpl(makePublicDir, getWorkspace)
	return makeProblemDirImpl
}

func InitializeGetProblemIds() helper.GetProblemIds {
	getProblemIdsImpl := helper.NewGetProblemIdsImpl()
	return getProblemIdsImpl
}

func InitializeInitService() service.InitService {
	getProblemIds := InitializeGetProblemIds()
	makeProblemDir := InitializeMakeProblemDir()
	initServiceImpl := service.NewInitServiceImpl(getProblemIds, makeProblemDir)
	return initServiceImpl
}

func InitializeInitCli() *cli.InitCli {
	console := InitializeConsole()
	initService := InitializeInitService()
	initCli := cli.NewInitCli(console, initService)
	return initCli
}
