// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ppdx999/kyopro/internal/cli"
	"github.com/ppdx999/kyopro/internal/infra"
	"github.com/ppdx999/kyopro/internal/service"
	"github.com/ppdx999/kyopro/internal/service/helper"
)

// Injectors from wire.go:

func InitializeGetWorkspaceImpl() *helper.GetWorkspaceImpl {
	fsImpl := infra.NewFsImple()
	getWorkspaceImpl := helper.NewGetWorkspaceImpl(fsImpl)
	return getWorkspaceImpl
}

func InitializeMakeProblemDirImpl() *helper.MakeProblemDirImpl {
	fsImpl := infra.NewFsImple()
	getWorkspaceImpl := InitializeGetWorkspaceImpl()
	makeProblemDirImpl := helper.NewMakeProblemDirImpl(fsImpl, getWorkspaceImpl)
	return makeProblemDirImpl
}

func InitializeInitServiceImpl() *service.InitServiceImpl {
	getProblemIdsImpl := helper.NewGetProblemIdsImpl()
	makeProblemDirImpl := InitializeMakeProblemDirImpl()
	initServiceImpl := service.NewInitServiceImpl(getProblemIdsImpl, makeProblemDirImpl)
	return initServiceImpl
}

func InitializeInitCli() *cli.InitCli {
	consoleImpl := infra.NewConsoleImpl()
	initServiceImpl := InitializeInitServiceImpl()
	initCli := cli.NewInitCli(consoleImpl, initServiceImpl)
	return initCli
}
